### ISSUE TITLE
  How does this code calculate RG (P% / #) ,CS (P% / R%), CO evaluation indexes. 

### ISSUE THREAD

**Issue by hdb1301040027** [aistairc/sports-reporter#2]
Another problem is that the only blue I get in gtx760 is (no writer 15.7, writer 16.7) and gtx2080ti (no writer 15.4, writer 15.7),. How can I improve blue? Thank you！

**Comment by isomap** [comment]
Sorry for the late response.
Could you give me more information?
Did you use the pre-trained model? or train from scratch?
How to run these codes?

**Comment by isomap** [comment]
wrt your first question, you can refer to the following repo: https://github.com/harvardnlp/data2text
